### ISSUE TITLE
error  Import this project   jitsi-meet-electron-utils  

### ISSUE THREAD

**Issue by zhangzhoufei** [jitsi/jitsi-meet-electron-utils#60]
1. my project   name  Electron-vue ，Import this project   jitsi-meet-electron-utils
2. package.js --->
 "dependencies": {
     "electron": "^6.0.12",
    "jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils#v1.0.2"
     ......

3. npm install github:jitsi/jitsi-meet-electron-utils#v1.0.2

4. error:
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
× Install fail! Error: EEXIST: file already exists, symlink 'G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_robotjs@0.5.1@robotjs' -> 'G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\robotjs'
Error: EEXIST: file already exists, symlink 'G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_robotjs@0.5.1@robotjs' -> 'G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\robotjs'
npminstall version: 3.23.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\mynames\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js rebuild jitsi-meet-electron-utils@1.0.2 robotjs@0.5.1 robotjs@0.5.1

    at ChildProcess.<anonymous> (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
From previous event:
    at _rebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\src\cli\install-app-deps.ts:58:9
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at _installAppDeps (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\out\cli\install-app-deps.js:177:26)
    at installAppDeps (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\out\cli\install-app-deps.js:146:26)
    at G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\src\cli\cli.ts:49:19
[npminstall:runscript:error] xiaomi@0.0.0 scripts.postinstall run "electron-builder install-app-deps" error: Error [RunScriptError]: Run "C:\Windows\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\mynames\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  name: 'RunScriptError',
  stdio: [Object]
}
× Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
RunScriptError: Run "C:\Windows\system32\cmd.exe /d /s /c electron-builder install-app-deps" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\mynames\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npminstall version: 3.23.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\mynames\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\mynames\.cnpmrc --disturl=https://npm.taob
ao.org/mirrors/node --registry=https://r.npm.taobao.org

G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project>npm run postinstall

> xiaomi@0.0.0 postinstall G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project
> electron-builder install-app-deps

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> jitsi-meet-electron-utils@1.0.2 install G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_jitsi-meet-electron-utils@1.0.2@jitsi-meet-electron-utils
> prebuild-install || node-gyp rebuild

G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_jitsi-meet-electron-utils@1.0.2@jitsi-meet-electron-utils>"node"  "G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_jitsi-meet-electron-utils@1.0.2@ji
tsi-meet-electron-utils\node_modules\.bin\\..\..\..\_prebuild-install@5.3.2@prebuild-install\bin.js"

> robotjs@0.5.1 install G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_robotjs@0.5.1@robotjs
> node-gyp rebuild

G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_robotjs@0.5.1@robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\nod
e-gyp\bin\node-gyp.js" rebuild )  else (node "node C:\Users\me\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Error output:
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\_robotjs@0.5.1@robotjs\node C:\Users\me\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mynames\AppData\Roaming\npm-cache\_logs\2019-10-18T08_03_59_992Z-debug.log

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
    at ChildProcess.<anonymous> (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:300:26)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
From previous event:
    at _rebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\src\util\yarn.ts:20:11
From previous event:
    at _installOrRebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\src\cli\install-app-deps.ts:58:9
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at _installAppDeps (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\out\cli\install-app-deps.js:177:26)
    at installAppDeps (G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\out\cli\install-app-deps.js:146:26)
    at G:\webstromProject\MoNaoXiaoMi\XiaoMiCode\my-project\node_modules\electron-builder\src\cli\cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xiaomi@0.0.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xiaomi@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mynames\AppData\Roaming\npm-cache\_logs\2019-10-18T08_04_00_086Z-debug.log

**Comment by saghul** [comment]
What node version are you using?

**Comment by zhangzhoufei** [comment]
> What node version are you using?

--- electron-vue； window； node 12.12.0 ；electron 6.0.12；

**Comment by saghul** [comment]
Oh, no idea then. @hristoterezov may know, but he is off today.

**Comment by zhangzhoufei** [comment]
> Oh, no idea then. @hristoterezov may know, but he is off today.

Thank you. This question has bothered me for a long time, @ hristoterezov, please reply to me.

@Hristoterezov if you see it, please reply to me thank you

**Comment by yasirmturk** [comment]
Why we are unable to build the electron on mac for windows or linux if we include `jitsi-meet-electron-utils` in dependency

**Comment by saghul** [comment]
There are no binary releases for all Electron versions, this is due to robotjs. You need the native environment to be able to compile those packages.
